<?php

namespace Database\Seeders;

use App\Models\ContainerShipment;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ContainerShipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $shipments = [
            [
                'skp_site' => 'S4',
                'container_type' => 'Container',
                'container_number' => 'UETU5627063',
                'shipment_date' => '2025-12-17',
                'country' => 'TURKEY',
                'forwarder' => 'CEVA',
                'hauler' => 'NTL',
                'sku_number' => '410624-01',
                'container_size' => '40HC',
                'model' => 'X664',
                'work_order' => '800090952',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S4',
                'container_type' => 'Container',
                'container_number' => 'MRSU6895764',
                'shipment_date' => '2025-12-17',
                'country' => 'TAIWAN',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '410623-01',
                'container_size' => '40HC',
                'model' => 'X664',
                'work_order' => '800090825',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'UETU2947335',
                'shipment_date' => '2025-12-17',
                'country' => 'WEST CHINA',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '481768-01',
                'container_size' => '20GP',
                'model' => 'X285L',
                'work_order' => '800090739',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S4',
                'container_type' => 'Container',
                'container_number' => 'MRSU5049442',
                'shipment_date' => '2025-12-17',
                'country' => 'TAIWAN',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '586175-01',
                'container_size' => '40HC',
                'model' => 'X664',
                'work_order' => '800090818',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'WHSU6609074',
                'shipment_date' => '2025-12-17',
                'country' => 'YACHIYO',
                'forwarder' => 'DHL',
                'hauler' => 'ZENO',
                'sku_number' => '400404-01',
                'container_size' => '40HC',
                'model' => 'X285K',
                'work_order' => '800091039',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'CAAU9352660',
                'shipment_date' => '2025-12-17',
                'country' => 'POLAND',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '545007-01',
                'container_size' => '40HC',
                'model' => 'PH05',
                'work_order' => '800090869',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'MRSU3286785',
                'shipment_date' => '2025-12-17',
                'country' => 'YACHIYO',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '496012-01',
                'container_size' => '40HC',
                'model' => 'X620D',
                'work_order' => '800091050',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'MRSU7859479',
                'shipment_date' => '2025-12-17',
                'country' => 'YACHIYO',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '492668-01',
                'container_size' => '40HC',
                'model' => 'X620D',
                'work_order' => '800091049',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'TCKU6781730',
                'shipment_date' => '2025-12-16',
                'country' => 'TURKEY',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '448884-01',
                'container_size' => '40HC',
                'model' => 'X620D',
                'work_order' => '800090754',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'MRSU7490101',
                'shipment_date' => '2025-12-17',
                'country' => 'POLAND',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '545007-01',
                'container_size' => '40HC',
                'model' => 'PH05',
                'work_order' => '800090701',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'CAAU7232769',
                'shipment_date' => '2025-12-16',
                'country' => 'TURKEY',
                'forwarder' => 'MAERSK',
                'hauler' => 'NARITA',
                'sku_number' => '448884-01',
                'container_size' => '40HC',
                'model' => 'X620D',
                'work_order' => '800090752',
                'high_sec' => true,
            ],
            [
                'skp_site' => 'S2',
                'container_type' => 'Container',
                'container_number' => 'KOCU2009467',
                'shipment_date' => '2025-12-16',
                'country' => 'UK',
                'forwarder' => 'DHL',
                'hauler' => 'ZENO',
                'sku_number' => '145689-01',
                'container_size' => '20GP',
                'model' => '60SC-901',
                'work_order' => '800091060',
                'high_sec' => true,
            ],
        ];

        foreach ($shipments as $shipment) {
            ContainerShipment::create($shipment);
        }
    }
}
